prerequisits:
- name: spark
  pods:
  - name: argo
    # bubble up whether or not the pod is ready
    # support regex
  crds:
  - group: sparkoperator.k8s.io
    kind: SparkApplication
    version: v1beta2
  - group: acme.cert-manager.io
    kind: Challenges
    version: v1
